### ISSUE TITLE
This gem should be pushed as 1.0.0

### ISSUE THREAD

**Issue by krainboltgreene** [juskoljo/toki#1]
It seems to do at the very least the minimum amount it set out to complete and has been pushed for public assumption. This gem isn't v0.0.3, it's at least 1.0.0 by any logical versioning system.

I almost assumed that a version condition library at v0.0.3 was a joke.

**Comment by juskoljo** [comment]
Thank you for the feedback; now as project being almost two days old it might be reasonable to bump the version to 1.0.0 ;).
